- name: Install DNS Server Role
  ansible.windows.win_feature:
    name: DNS
    state: present
    include_management_tools: yes
  register: dns_install

- name: Reboot after installing DNS Server Role
  ansible.windows.win_reboot:
  when: dns_install.changed

# --- Forward Lookup Zone ---
- name: Create Forward Lookup Zone
  community.windows.win_dns_zone:
    name: jurassicpark.local
    type: Primary
  ignore_errors: yes

# --- A Records for Tyrannosaurus Servers ---
- name: Create A records for Tyrannosauruses
  community.windows.win_dns_record:
    name: "tyrannosaurus{{ item.number }}"
    type: A
    value: "10.0.{{ item.number }}.9"
    zone: jurassicpark.local
    state: present
  loop:
    - { number: 1 }
    - { number: 2 }
  ignore_errors: yes

# --- Reverse Lookup Zones ---
- name: Create Reverse Lookup Zones
  community.windows.win_dns_zone:
    name: "{{ item.zone }}"
    type: Primary
  loop:
    - { zone: "1.0.10.in-addr.arpa" }
    - { zone: "2.0.10.in-addr.arpa" }
  ignore_errors: yes

# --- PTR Records for Tyrannosaurus Servers ---
- name: Create PTR records for Tyrannosauruses
  community.windows.win_dns_record:
    name: "9"
    type: PTR
    value: "tyrannosaurus{{ item.number }}.jurassicpark.local"
    zone: "{{ item.number }}.0.10.in-addr.arpa"
    state: present
  loop:
    - { number: 1 }
    - { number: 2 }
  ignore_errors: yes