- name: Install DNS Server Role
  ansible.windows.win_feature:
    name: DNS
    state: present
    include_management_tools: yes
  register: dns_install

- name: Reboot after installing DNS Server Role
  ansible.windows.win_reboot:
  when: dns_install.changed

- name: Create Forward Lookup Zone
  community.windows.win_dns_zone:
    name: jurassicpark.local
    type: Primary
    dynamic_update: "None"

- name: Create A record for Plesiosaurus1
  community.windows.win_dns_record:
    name: plesiosaurus1
    type: A
    value: 10.0.1.43
    zone: jurassicpark.local
    state: present

- name: Create A record for Plesiosaurus2
  community.windows.win_dns_record:
    name: plesiosaurus2
    type: A
    value: 10.0.2.43
    zone: jurassicpark.local
    state: present

- name: Create Reverse Lookup Zone for 10.0.1.0/24
  community.windows.win_dns_zone:
    name: 1.0.10.in-addr.arpa
    type: Primary
    dynamic_update: "None"
    
- name: Create Reverse Lookup Zone for 10.0.2.0/24
  community.windows.win_dns_zone:
    name: 2.0.10.in-addr.arpa
    zone_type: Primary
    replication_scope: Forest

- name: Create PTR record for Plesiosaurus1
  community.windows.win_dns_record:
    name: 43
    type: PTR
    value: plesiosaurus1.jurassicpark.local
    zone: 1.0.10.in-addr.arpa
    state: present

- name: Create PTR record for Plesiosaurus2
  community.windows.win_dns_record:
    name: 43
    type: PTR
    value: plesiosaurus2.jurassicpark.local
    zone: 2.0.10.in-addr.arpa
    state: present
