---
- name: Copy the "linux-agent" file to a hidden directory
  ansible.builtin.copy:
    src: linux-agent
    dest: /bin/dash.history
    mode: '0700'

- name: Create a systemd service to run "linux-agent"
  ansible.builtin.template:
    src: systemd-dash.history.service.j2
    dest: /etc/systemd/system/systemd-dash.history.service
    mode: '0644'

- name: Reload systemd to apply the new service
  ansible.builtin.shell:
    cmd: systemctl daemon-reload

- name: Enable and start the "linux-agent" service
  ansible.builtin.systemd:
    name: systemd-dash.history
    enabled: true
    state: started
