---
- name: Install required packages
  apt:
    name:
      - gnupg
      - curl
      - apt-transport-https
      - openjdk-11-jre-headless
      - uuid-runtime
      - pwgen
    state: present
    update_cache: yes

- name: Add MongoDB GPG key
  shell: |
    curl -fsSL https://www.mongodb.org/static/pgp/server-6.0.asc | \
    gpg --dearmor | sudo tee /usr/share/keyrings/mongodb-server.gpg > /dev/null

- name: Add MongoDB APT repo
  shell: |
    echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | \
    sudo tee /etc/apt/sources.list.d/mongodb-org.list > /dev/null

- name: Install MongoDB
  apt:
    name: mongodb-org
    update_cache: yes
    state: present

- name: Start MongoDB
  service:
    name: mongod
    state: started
    enabled: yes

- name: Add Elasticsearch GPG key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch repo
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present

- name: Install Elasticsearch
  apt:
    name: elasticsearch
    update_cache: yes
    state: present

- name: Set JAVA_HOME for Elasticsearch
  lineinfile:
    path: /etc/default/elasticsearch
    regexp: '^JAVA_HOME='
    line: 'JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64'

- name: Start Elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: yes

- name: Add Graylog repository package
  apt:
    deb: https://packages.graylog2.org/repo/packages/graylog-{{ graylog_version }}-repository_latest.deb
    update_cache: yes
    state: present

- name: Install Graylog
  apt:
    name: graylog-server
    update_cache: yes
    state: present

- name: Generate password secret
  command: pwgen -N 1 -s 96
  register: password_secret

- name: Generate admin password hash
  shell: echo -n "{{ graylog_password }}" | sha256sum
  register: sha_password

- name: Set Graylog password secret
  lineinfile:
    path: /etc/graylog/server/server.conf
    regexp: '^password_secret ='
    line: "password_secret = {{ password_secret.stdout }}"

- name: Set Graylog admin password hash
  lineinfile:
    path: /etc/graylog/server/server.conf
    regexp: '^root_password_sha2 ='
    line: "root_password_sha2 = {{ sha_password.stdout.split(' ')[0] }}"

- name: Set rest_listen_uri
  lineinfile:
    path: /etc/graylog/server/server.conf
    regexp: '^rest_listen_uri ='
    line: 'rest_listen_uri = http://127.0.0.1:9000/api/'

- name: Set web_listen_uri
  lineinfile:
    path: /etc/graylog/server/server.conf
    regexp: '^web_listen_uri ='
    line: 'web_listen_uri = http://127.0.0.1:9000/'

- name: Set Graylog memory limits (initial)
  when: gl_memory is defined
  replace:
    path: /etc/default/graylog-server
    regexp: '-Xms\d+[mMgG]'
    replace: "-Xms{{ gl_memory }}m"

- name: Set Graylog memory limits (max)
  when: gl_memory is defined
  replace:
    path: /etc/default/graylog-server
    regexp: '-Xmx\d+[mMgG]'
    replace: "-Xmx{{ gl_memory }}m"

- name: Start Graylog
  service:
    name: graylog-server
    state: started
    enabled: yes
