### BIND DNS SETUP ###
- name: Install BIND and dependencies for DNS
  package:
    name:
      - bind
      - bind-utils
    state: present

- name: Configure BIND options
  copy:
    dest: /etc/named.conf
    content: |
      options {
          listen-on port 53 { 127.0.0.1; {{ dns_zones[inventory_hostname]['server_ip'] }}; };
          listen-on-v6 port 53 { ::1; };
          directory "/var/named";
          dump-file "/var/named/data/cache_dump.db";
          statistics-file "/var/named/data/named_stats.txt";
          memstatistics-file "/var/named/data/named_mem_stats.txt";
          allow-query { any; };
          recursion no;
          max-cache-size 512M;
      };
      zone "{{ dns_zones[inventory_hostname]['zone_name'] }}" IN {
          type master;
          file "/var/named/{{ dns_zones[inventory_hostname]['zone_name'] }}.zone";
      };

- name: Create DNS zone file for the team
  copy:
    dest: /var/named/{{ dns_zones[inventory_hostname]['zone_name'] }}.zone
    content: |
      $TTL 86400
      @   IN  SOA {{ dns_zones[inventory_hostname]['hosts'][0]['name'] }}.{{ dns_zones[inventory_hostname]['zone_name'] }}. admin.{{ dns_zones[inventory_hostname]['zone_name'] }}. (
            2025040701 ; Serial
            3600       ; Refresh
            1800       ; Retry
            1209600    ; Expire
            86400      ; Minimum TTL
      )
          IN  NS  {{ dns_zones[inventory_hostname]['hosts'][0]['name'] }}.{{ dns_zones[inventory_hostname]['zone_name'] }}.
      {% for host in dns_zones[inventory_hostname]['hosts'] %}
      {{ host.name }}    IN  A   {{ host.ip }}
      {% endfor %}

- name: Set permissions for DNS zone file
  file:
    path: /var/named/{{ dns_zones[inventory_hostname]['zone_name'] }}.zone
    owner: named
    group: named
    mode: 0640

- name: Restart and enable BIND
  systemd:
    name: named
    state: restarted
    enabled: yes