- name: Install AD-Domain-Services
  win_feature:
    name: AD-Domain-Services
    state: present
    include_management_tools: yes

- name: Promote Plesiosaurus to Domain Controller
  win_domain:
    dns_domain_name: jurassicpark.local
    domain_netbios_name: jurassicpark
    safe_mode_password: JurassicParkDSRM@2025
  register: promote

- name: Reboot after domain promotion
  win_reboot:
  when: promote.changed

- name: Create local users on Plesiosaurus
  win_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    state: present
  loop: "{{ jurassic_users }}"
  #Creates AD users
- name: Create AD users on Plesiosaurus
  win_domain_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    user_principal_name: "{{ item.name }}@jurassicpark.local"
    state: present
    path: "OU=Users,DC=jurassicpark,DC=local"
    enabled: yes
    groups: "{{ 'Domain Admins' if item.admin else '' }}"
  loop: "{{ jurassic_users }}"
