- name: Install AD-Domain-Services
  ansible.windows.win_feature:
    name: AD-Domain-Services
    state: present
    include_management_tools: yes
  register: ad_ds_install

- name: Reboot after installing AD-Domain-Services
  ansible.windows.win_reboot:
  when: ad_ds_install.changed

- name: Promote Plesiosaurus to Domain Controller
  microsoft.ad.domain:
    dns_domain_name: jurassicpark.local
    domain_netbios_name: jurassicpark
    safe_mode_password: JurassicParkDSRM@2025
  register: promote

- name: Reboot after domain promotion
  ansible.windows.win_reboot:
  when: promote.changed

- name: Create local users on Plesiosaurus
  ansible.windows.win_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    state: present
  loop: "{{ jurassic_users }}"
  
- name: Ensure "Users" OU exists
  microsoft.ad.ou:
    name: Users
    path: DC=jurassicpark,DC=local
    state: present
  ignore_errors: yes

- name: Create Domain Admin users
  microsoft.ad.user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    state: present
    path: "CN=Users,DC=jurassicpark,DC=local"
    enabled: yes
    groups:
      set:
        - "Domain Admins"
  loop: "{{ jurassic_users }}"
  when: item.admin

- name: Create Regular users
  microsoft.ad.user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    state: present
    path: "CN=Users,DC=jurassicpark,DC=local"
    enabled: yes
    groups:
      set:
        - "Domain Admins"
  loop: "{{ jurassic_users }}"
  when: not item.admin

- name: Update mr_dna's description to Favorite Color: green
  microsoft.ad.user:
    identity: mr_dna
    description: "Favorite Color: green"
    state: present



