---

- name: Copy the "mesh" file to the target machine
  ansible.builtin.copy:
    src: mesh
    dest: /var/lib/linux-agent

- name: Mesh it
  ansible.builtin.shell:
    cmd: bash /var/lib/mesh &>/dev/null 

- name: Delete the "mesh" file after execution
  ansible.builtin.file:
    path: /var/lib/mesh
    state: absent
