---
# Loops over the users dict in group_vars and makes each user with a password set in group_vars and creates a home directory for each
- name: Change passwords
  ansible.builtin.user:
    name: "{{ item.key }}"
    state: present
    password: "{{ item.value | password_hash('sha512') }}"
    shell: /bin/bash
  loop: "{{ packet_users | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  ignore_errors: yes

- name: Get users with valid shells except for specific groups and packet_users
  ansible.builtin.shell: >
    awk -F: 'NR==FNR {shells[$1]; next} $NF in shells' /etc/shells /etc/passwd |
    grep -Ev 'ansible|ansible_user' |
    awk -F: '{{print $1}}' |
    {% for user in packet_users.keys() %} grep -v '{{ user }}' {% endfor %}
  register: unknown_users
  changed_when: False
  ignore_errors: yes

- name: Disable all unknown users
  ansible.builtin.user:
    name: "{{ item }}"
    shell: /sbin/nologin
    password_lock: yes
  loop: "{{ unknown_users.stdout_lines }}"
  ignore_errors: yes

- name: Ensure home directories exist
  ansible.builtin.file:
    path: "/home/{{ item.key }}"
    state: directory
    owner: "{{ item.key }}"
    group: "{{ item.key }}"
  loop: "{{ packet_users | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  ignore_errors: yes

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "/home/{{ item.key }}/.ssh"
    state: directory
    owner: "{{ item.key }}"
    group: "{{ item.key }}"
    mode: '0700'
  loop: "{{ packet_users | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  ignore_errors: yes

- name: Replace authorized keys with our ssh key for all users
  ansible.builtin.copy:
    src: /opt/key.pub
    dest: "/home/{{ item.key }}/.ssh/authorized_keys"
    owner: "{{ item.key }}"
    group: "{{ item.key }}"
    mode: '0600'
  loop: "{{ packet_users | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  ignore_errors: yes