---

- name: Users
  hosts: all
  become: yes
  roles:
    - users
  tags:
    - never
    - linux
    - users

- name: knockd
  hosts: all
  become: yes
  roles:
    - knockd
  tags:
    - never
    - linux
    - knockd