[all]
Plesiosaurus1 ansible_host=10.0.1.43
Plesiosaurus2 ansible_host=10.0.2.43
Tyrannosaurus1 ansible_host=10.0.1.9
Tyrannosaurus2 ansible_host=10.0.2.9

[team01]
Plesiosaurus1 ansible_host=10.0.1.43
Tyrannosaurus1 ansible_host=10.0.1.9

[team02]
Plesiosaurus2 ansible_host=10.0.2.43
Tyrannosaurus2 ansible_host=10.0.2.9

[ad]
Tyrannosaurus1 ansible_host=10.0.1.9
Tyrannosaurus2 ansible_host=10.0.2.9

[dns]
Plesiosaurus1 ansible_host=10.0.1.43
Plesiosaurus2 ansible_host=10.0.2.43

[all:vars]
ansible_user=ansible
ansible_password=ansible
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore
ansible_winrm_transport=ntlm
