- name: ad
  hosts: ad
  collections:
    - ansible.windows
    - microsoft.ad
    - community.windows
  roles:
    - ad
  tags: 
    - never
    - deploy
    - ad

- name: dns
  hosts: dns
  collections:
    - ansible.windows
    - microsoft.ad
    - community.windows
  become: yes
  roles:
    - dns
  tags: 
    - never
    - deploy
    - dns