- name: ad
  hosts: ad
  collections:
    - microsoft.ad
    - ansible.windows
  roles:
    - ad
  tags: 
    - never
    - deploy
    - ad

# - name: dns
#   hosts: dns
#   collections:
#     - microsoft.ad
#     - community.windows
#   become: yes
#   roles:
#     - dns
#   tags: 
#     - never
#     - deploy
#     - dns