---
#users vars
users:
  grayteam: cdt-grayteamOnly!
  scoring: scoring123
  ian_malcolm: lifeUhFindsAWay94!
  john_hammon: welcomeToJurrasicPark00!
  mr_dna: blueprintOfLife54!
  ellie_sattler: dinosaurDroppings72!
  alan_grant: itsADinosaur68!


#mysql
mysql_root_password: "SecureRootPass"
mysql_user: "scoring"
mysql_user_password: "query123"

