---
#users vars
admin_users:
  ian_malcolm: lifeUhFindsAWay94!
  john_hammon: welcomeToJurrasicPark00!
  mr_dna: blueprintOfLife54!
  scoring: scoring123
  
users:
  ellie_sattler: dinosaurDroppings72!
  alan_grant: itsADinosaur68!
  
#freeipa vars
#realm_name: "JURPARK.COM"
#domain_name: "jurpark.com"
#admin_password: "Password123!"
#dm_password: "Password123!" 