---
#users vars
users:
  grayteam: cdt-grayteamOnly!
  scoring: scoring123
  ian_malcolm: lifeUhFindsAWay94!
  john_hammon: welcomeToJurrasicPark00!
  mr_dna: blueprintOfLife54!
  ellie_sattler: dinosaurDroppings72!
  alan_grant: itsADinosaur68!

#freeipa
dns_zones:
  team01:
    server_ip: "10.0.1.1"
    zone_name: "jp1.local"
    hosts:
      - { name: "giganotosaurus1", ip: "10.0.1.1" }
      - { name: "brachiosaurus1", ip: "192.168.1.89" }
      - { name: "stegosaurus1", ip: "192.168.1.109" }
      - { name: "triceratops1", ip: "192.168.1.12" }
      - { name: "allosaurus1", ip: "10.0.1.77" }
  team02:
    server_ip: "10.0.2.1"
    zone_name: "jp2.local"
    hosts:
      - { name: "giganotosaurus2", ip: "10.0.2.1" }
      - { name: "brachiosaurus2", ip: "192.168.2.89" }
      - { name: "stegosaurus2", ip: "192.168.2.109" }
      - { name: "triceratops2", ip: "192.168.2.12" }
      - { name: "allosaurus2", ip: "10.0.2.77" 

#mysql
mysql_root_password: "blueprintOfLife54!"
mysql_user: "mr_dna"
mysql_user_password: "blueprintOfLife54!"

#dovecot
thunderbird_username: "john_hammond"
thunderbird_password: "jhamm123"

#graylog
graylog_password: "graylog" 
graylog_version: 5.0
gl_memory: 1024