---
- name: find flags 5pt
  ansible.builtin.shell: >
    grep -ri --exclude-dir=proc --exclude-dir=sys CTF_5PT / 2>/dev/null | grep -v '^Binary file ' | awk '{print $NF}' | sort | uniq
  register: result_5pt
  ignore_errors: yes

- name: find flags 3pt
  ansible.builtin.shell: >
    grep -ri --exclude-dir=proc --exclude-dir=sys CTF_3PT / 2>/dev/null | grep -v '^Binary file ' | awk '{print $NF}' | sort | uniq
  register: result_3pt
  ignore_errors: yes

- name: find flags 1pt
  ansible.builtin.shell: >
    grep -ri --exclude-dir=proc --exclude-dir=sys CTF_1PT / 2>/dev/null | grep -v '^Binary file ' | awk '{print $NF}' | sort | uniq
  register: result_1pt
  ignore_errors: yes