---
- name: find flags 5pt
  ansible.builtin.shell: >
    grep -ri --exclude-dir=proc --exclude-dir=sys CTF_5PT / 2>/dev/null | grep -v '^Binary file ' | awk '{print $NF}' | sort | uniq
  register: result_5pt
  ignore_errors: yes

- name: find flags 3pt
  ansible.builtin.shell: >
    grep -ri --exclude-dir=proc --exclude-dir=sys CTF_3PT / 2>/dev/null | grep -v '^Binary file ' | awk '{print $NF}' | sort | uniq
  register: result_3pt
  ignore_errors: yes

- name: find flags 1pt
  ansible.builtin.shell: >
    grep -ri --exclude-dir=proc --exclude-dir=sys CTF_1PT / 2>/dev/null | grep -v '^Binary file ' | awk '{print $NF}' | sort | uniq
  register: result_1pt
  ignore_errors: yes

- name: print flags 5pt
  ansible.builtin.debug:
    var: result_5pt.stdout_lines

- name: print flags 3pt
  ansible.builtin.debug:
    var: result_3pt.stdout_lines

- name: print flags 1pt
  ansible.builtin.debug:
    var: result_1pt.stdout_lines


- name: Remove grep on Debian-based systems (Ubuntu, Kali)
  ansible.builtin.apt:
    name: grep
    state: absent
  when: ansible_os_family == "Debian"

- name: Remove grep on Arch-based systems (Arch)
  ansible.builtin.pacman:
    name: grep
    state: absent
  when: ansible_distribution == "Archlinux"

- name: Remove grep on RedHat-based systems (Fedora, Rocky)
  ansible.builtin.dnf:
    name: grep
    state: absent
  when: ansible_os_family == "RedHat"