---
- name: Set the hostname for team01 machines
  hostname:
    name: "{{ inventory_hostname }}"
  when: "'team01' in ansible_limit"

- name: Set the hostname for team02 machines
  hostname:
    name: "{{ inventory_hostname }}"
  when: "'team02' in ansible_limit"

### DNS CONFIGURATION ###
- name: Set primary DNS server
  lineinfile:
    path: /etc/resolv.conf
    state: present
    line: "nameserver 100.65.0.254"

- name: Empty the /etc/hosts file
  copy:
    content: ""
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644


- name: Configure /etc/hosts file for team01
  lineinfile:
    path: /etc/hosts
    state: present
    line: "{{ item }}"
  when: "'team01' in ansible_limit"
  loop:
    - "10.0.1.1 Gigantosaurus1"
    - "192.168.1.89 Brachiosaurus1"
    - "192.168.1.109 Stegosaurus1"
    - "192.168.1.12 Triceratops1"
    - "10.0.1.77 Allosaurus1"

- name: Configure /etc/hosts file for team02
  lineinfile:
    path: /etc/hosts
    state: present
    line: "{{ item }}"
  when: "'team02' in ansible_limit"
  loop:
    - "10.0.1.1 Gigantosaurus2"
    - "192.168.1.89 Brachiosaurus2"
    - "192.168.1.109 Stegosaurus2"
    - "192.168.1.12 Triceratops2"
    - "10.0.1.77 Allosaurus2"