[all]
10.0.1.77     #Team01 Allosaurus Debian 12
10.0.2.77     #Team02 Allosaurus Debian 12
10.0.1.1      #Team01 Giganotosaurus Fedora 4.1
10.0.2.1      #Team02 Giganotosaurus Fedora 4.1
192.168.1.12  #Team01 Triceratops Rocky 9
192.168.2.12  #Team02 Triceratops Rocky 9
192.168.1.89  #Team01 Brachiosaurus Debian 11
192.168.2.89  #Team02 Brachiosaurus Debian 11
192.168.1.109 #Team01 Stegosaurus Ubuntu 22
192.168.2.109 #Team02 Stegosaurus Ubuntu 22

[local]
10.0.1.77     #Team01 Allosaurus Debian 12
10.0.2.77     #Team02 Allosaurus Debian 12
10.0.1.1      #Team01 Giganotosaurus Fedora 4.1
10.0.2.1      #Team02 Giganotosaurus Fedora 4.1

[cloud]
192.168.1.12  #Team01 Triceratops Rocky 9
192.168.2.12  #Team02 Triceratops Rocky 9
192.168.1.89  #Team01 Brachiosaurus Debian 11
192.168.2.89  #Team02 Brachiosaurus Debian 11
192.168.1.109 #Team01 Stegosaurus Ubuntu 22
192.168.2.109 #Team02 Stegosaurus Ubuntu 22

[team01]
giganotosaurus1.jp1.local ansible_host=10.0.1.1
brachiosaurus1.jp1.local ansible_host=192.168.1.89
stegosaurus1.jp1.local ansible_host=192.168.1.109
triceratops1.jp1.local ansible_host=192.168.1.12
allosaurus1.jp1.local ansible_host=10.0.1.77

[team02]
giganotosaurus2.jp2.local ansible_host=10.0.2.1
brachiosaurus2.jp2.local ansible_host=192.168.2.89
stegosaurus2.jp2.local ansible_host=192.168.2.109
triceratops2.jp2.local ansible_host=192.168.2.12
allosaurus2.jp2.local ansible_host=10.0.2.77

[team01_local]
10.0.1.77     #Team01 Allosaurus Debian 12
10.0.1.1      #Team01 Giganotosaurus Fedora 4.1

[team01_cloud]
192.168.1.12  #Team01 Triceratops Rocky 9
192.168.1.89  #Team01 Brachiosaurus Debian 11
192.168.1.109 #Team01 Stegosaurus Ubuntu 22

[team02_local]
10.0.2.77     #Team02 Allosaurus Debian 12
10.0.2.1      #Team02 Giganotosaurus Fedora 4.1

[team02_cloud]
192.168.2.12  #Team02 Triceratops Rocky 9
192.168.2.89  #Team02 Brachiosaurus Debian 11
192.168.2.109 #Team02 Stegosaurus Ubuntu 22

[thunderbird]
10.0.1.77     #Team01 Allosaurus Debian 12
10.0.2.77     #Team02 Allosaurus Debian 12

[freeipa]
10.0.1.1      #Team01 Giganotosaurus Fedora 4.1
10.0.2.1      #Team02 Giganotosaurus Fedora 4.1

[nginx]
192.168.1.12  #Team01 Triceratops Rocky 9
192.168.2.12  #Team02 Triceratops Rocky 9

[vsftpd]
192.168.1.89  #Team01 Brachiosaurus Debian 11
192.168.2.89  #Team02 Brachiosaurus Debian 11

[mysql]
192.168.1.109 #Team01 Stegosaurus Ubuntu 22
192.168.2.109 #Team02 Stegosaurus Ubuntu 22

[team01:vars]
email_domain=jurassicpark1.com
thunderbird_username=john_hammond
thunderbird_password=jhamm123  # Use Ansible Vault for security

[team02:vars]
email_domain=jurassicpark2.com
thunderbird_username=john_hammond
thunderbird_password=jhamm123  # Use Ansible Vault for security


[all:vars]
ansible_user=ansible
ansible_password=ansible
ansible_become_password=ansible
ansible_ssh_private_key_file=~/.ssh/id_rsa 
ssh_port=22
ansible_ssh_common_args='-o StrictHostKeyChecking=no'