---

- name: Set up Users
  hosts: all
  become: yes
  roles:
    - users
  tags:
    - never
    - deploy
    - users

- name: thunderbird
  hosts: thunderbird
  become: yes
  roles:
    - thunderbird
  tags: 
    - never
    - deploy
    - thunderbird

- name: freeipa
  hosts: all
  become: yes
  roles:
    - freeipa
  tags: 
    - never
    - deploy
    - freeipa

- name: nginx
  hosts: nginx
  become: yes
  roles:
    - nginx
  tags: 
    - never
    - deploy
    - nginx

- name: graylog
  hosts: graylog
  become: yes
  roles:
    - graylog
  tags: 
    - never
    - deploy
    - graylog

- name: mysql
  hosts: mysql
  become: yes
  roles:
    - mysql
  tags: 
    - never
    - deploy
    - mysql