---
- name: Install and Configure MySQL
  hosts: mysql_servers
  become: yes
  vars:
    mysql_root_password: "SecureRootPass"
    mysql_user: "scoring"
    mysql_user_password: "query123"

  tasks:
    - name: Install ufw
      apt:
        name: ufw
        state: present

    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present

    - name: Install pip dependencies
      apt:
        name:
          - python3
          - python3-distutils
          - curl
        state: present

    - name: Install pip3
      apt: 
        name:
          - python3-pip
        state: present

    - name: Install PyMySQL using pip3
      pip:
        name: PyMySQL
        executable: pip3

    - name: Start and Enable MySQL Service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Configure remote-access
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
      notify:
        - Restart MySQL

    - name: Set Scorify allow Port steg1
      ufw:
        rule: allow
        port: 3306
        proto: tcp
        from_ip: 192.168.1.252

    - name: Set Scorify allow Port steg2
      ufw:
        rule: allow
        port: 3306
        proto: tcp
        from_ip: 192.168.2.252

    - name: Enable ufw
      ufw:
        state: enabled

    - name: Set MySQL root password
      mysql_user:
        login_user: root
        login_password: ''
        user: root
        password: "{{ mysql_root_password }}"
        host_all: yes
      ignore_errors: yes

    - name: Drop Database if exists
      mysql_db:
        name: "Tyrannosaurus_Rex"
        state: absent
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create Database
      mysql_db:
        name: "Tyrannosaurus_Rex"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
    
    - name: Delete User Database if exists
      mysql_db:
        name: "users"
        state: "absent"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create User Database
      mysql_db:
        name: "users"
        state: "present"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create MySQL User
      mysql_user:
        name: "scoring"
        password: "query123"
        priv: "users.*:ALL"
        host: "%"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create Staff
      mysql_query:
        login_db: "Tyrannosaurus_Rex"
        query: 
          CREATE TABLE IF NOT EXISTS staff (
            id INT AUTO_INCREMENT PRIMARY KEY,
            name VARCHAR(100) NOT NULL,
            email VARCHAR(100) NOT NULL UNIQUE
          );
        login_unix_socket: /var/run/mysqld/mysqld.sock
    - name: Create Prey Table
      mysql_query: 
        login_db: "Tyrannosaurus_Rex"
        query:
          CREATE TABLE IF NOT EXISTS prey (
            id INT AUTO_INCREMENT PRIMARY KEY,
            prey_id INT NOT NULL,
            dinosaur VARCHAR(100) NOT NULL,
            FOREIGN KEY (prey_id) REFERENCES staff(id)
          );
        login_unix_socket: /var/run/mysqld/mysqld.sock  

    - name: Create User Table
      mysql_query:
        login_db: "users"
        query:
          CREATE TABLE IF NOT EXISTS users (
          id INT AUTO_INCREMENT PRIMARY KEY,
          name VARCHAR(20) NOT NULL
          );
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Insert User Data
      mysql_query:
        login_db: "users"
        query:
          INSERT INTO users (name) VALUES
          ('scoring'),
          ('Ian Malcolm'),
          ('Mr.DNA'),
          ('Dennis Nedry')
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Insert Sample Data
      mysql_query:
        login_db: "Tyrannosaurus_Rex"
        query:
          INSERT INTO staff (name, email) VALUES
          ('Alice', 'alice@example.com'),
          ('Bob', 'bob@example.com');
        login_unix_socket: /var/run/mysqld/mysqld.sock
    - name: Insert Prey Data
      mysql_query:
        login_db: "Tyrannosaurus_Rex"
        query: 
          INSERT INTO prey (prey_id, dinosaur) VALUES
          (1, 'Velociraptors'),
          (2, 'Humans');
        login_unix_socket: /var/run/mysqld/mysqld.sock
  handlers:
    - name: Restart MySQL
      service:
        name: mysql
        state: restarted
