---

packet_users:
    dave: Route9TestStays$
    homeowner: BoxesBusyMales?
    peashooter: Radar0Untie5Karma*
    squash: Loans6EbbVolvo-
    bonkchoy: Purse3BrandMicro#
    tanglekelp: Track0SwoopToday?
    