---

packet_users:
    sudo_make_me_sandwich: Route9TestStays$
    temporary_admin: BoxesBusyMales?
    dev_test: Radar0Untie5Karma*
    backup_agent: Loans6EbbVolvo-
    monitoring_user: Purse3BrandMicro#
    legacy_app: Track0SwoopToday?
    fip_service: Creek4Spurt5Males^
    api_gateway: PixelMilk1Lodge^
    db_cleanup: Foods6Blend8Flame*
    cache_server: KarmaLagQueen+
