---

packet_users:
    Dave: Route9TestStays$
    Homeowner: BoxesBusyMales?
    Peashooter: Radar0Untie5Karma*
    Squash: Loans6EbbVolvo-
    Bonkchoy: Purse3BrandMicro#
    Tanglekelp: Track0SwoopToday?
    