---
- name: Make sure VSFTPD is installed
  ansible.builtin.package:
    name: vsftpd
    state: present

- name: Copy over configuration file
  ansible.builtin.copy:
    src: vsftpd.conf
    dest: /etc/vsftpd.conf
    owner: root
    group: root
    mode: '0644'

- name: Copy over scored file
  ansible.builtin.copy:
    src: dinoplans.txt
    dest: /home/scoring/dinoplans.txt
    owner: scoring
    group: scoring 
    mode: '0644'

- name: Restart VSFTPD
  service:
    name: vsftpd
    state: restarted